config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 過去のお知らせ
  get 'notice', to: 'notice#index', as: :notice

  # 使い方
  get 'manual/exporter', to: 'manual#exporter'

  # インポート
  get 'import', to: 'import#index', as: :import
  post 'import/file', to: 'import#file'
  post 'import/generate_token', to: 'import#generate_token'

  # エクスポート
  get 'export', to: 'export#index', as: :export
  get 'export/admiral_statuses', to: 'export#admiral_statuses'
  get 'export/event_progress_statuses', to: 'export#event_progress_statuses'
  get 'export/cop_event_progress_statuses', to: 'export#cop_event_progress_statuses'
  get 'export/ship_statuses', to: 'export#ship_statuses'

  # 提督情報
  match 'admiral_info', to: 'admiral_info#index', via: [ :get, :post ]
  get 'admiral_info/event(/:event_no(/:period))', to: 'admiral_info#event'
  get 'admiral_info/cop_event(/:event_no)', to: 'admiral_info#cop_event'

  # 艦娘情報
  ## 表が主体のページ
  get 'ship_list', to: 'ship_list#index'
  get 'ship_list/slot', to: 'ship_list#slot'
  get 'ship_list/blueprint', to: 'ship_list#blueprint'
  ## グラフが主体のページ
  match 'ship_info/level', to: 'ship_info#level', via: [ :get, :post ]
  match 'ship_info/level_summary', to: 'ship_info#level_summary', via: [ :get, :post ]
  match 'ship_info/card', to: 'ship_info#card', via: [ :get, :post ]

  # 装備情報
  get 'equipment_list', to: 'equipment_list#index'
  match 'equipment_list/:book_no', to: 'equipment_list#show', via: [ :get, :post ]

  # 全提督との比較
  get 'global/ship_card_ownership', to: 'global#ship_card_ownership', as: :global_ship_card_ownership
  get 'global/ship_card_ownership/active/:def_of_active_users', to: 'global#ship_card_ownership'
  get 'global/ship_card_ownership/event/:event_no', to: 'global#event_ship_card_ownership'
  get 'global/event(/:event_no(/:period))', to: 'global#event'
  get 'global/cop_event(/:event_no)', to: 'global#cop_event'

  get 'friend', to: 'friend#index'

  # Admiral Stats について
  get 'about', to: 'about#index'

  # OmniAuth によるログイン・ログアウト
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # デバッグ用のログイン（development のみ有効）
  get 'sessions/debug_create/:uid/:nickname', to: 'sessions#debug_create'

  # 以下の記載を追加すると root_url メソッドも自動設定される
  root to: 'home#index'

  # Public play data
  scope '/@:url_name' do
    # 公開情報の種類が2種類以上になったら、リダイレクト処理を変更する
    get '/', to: redirect('/@%{url_name}/ship_list')
    get '/ship_list', to: 'public_ship_list#index'
    get '/equipment_list', to: 'public_equipment_list#index'
    match '/equipment_list/:book_no', to: 'public_equipment_list#show', via: [ :get, :post ]
  end
  # 古い URL を、互換性維持のために残す
  get 'admirals/:url_name/ship_list', to: redirect('/@%{url_name}'), constraints: { format: :html }

  # Settings
  scope 'settings' do
    get 'request_logs', to: 'request_log#index'
    get 'tokens', to: 'token#index'
    post 'tokens', to: 'token#create'
    get 'publications', to: 'publication#index'
    post 'publications', to: 'publication#create_or_update'
  end

  # API
  scope 'api/v1' do
    # Admiral Stats がインポート可能なファイル種別のリスト（snake_case）
    get 'import/file_types', to: 'api_import#file_types'

    # SEGA 公式からエクスポートしたプレイデータのインポート
    post 'import/:file_type/:timestamp', to: 'api_import#import', as: :api_import
  end

  # 上記のいずれにもマッチしなかった場合は、root にリダイレクト
  get '*unmatched_route', to: 'application#redirect_to_home'
end

app/controllers/ship_list_controller.rb
class ShipListController < ApplicationController
  before_action :authenticate

  def index
    set_meta_tags title: '艦娘一覧'

    # URL パラメータ 'all' が true の場合は、未配備の艦娘も表示
    if ActiveRecord::Type::Boolean.new.deserialize(params[:all])
      @ships = ShipMaster.all.to_a
    else
      @ships = ShipMaster.where('implemented_at <= ?', Time.now).to_a

      # 「改」があとから実装された艦娘について、ShipMaster を上書き
      UpdatedShipMaster.where('implemented_at <= ?', Time.now).each do |us|
        s = @ships.select{|s| s.book_no == us.book_no }.first
        if s
          @ships.delete(s)
          @ships.push(us)
        end
      end
    end

    # ship_cards および ship_statuses の両方が空の場合は true
    @is_blank = true

    # 取得済みのカードを調べた結果
    @cards = {}

    # カードの枚数の配列
    # 取得済みは :acquired、未取得は :not_acquired、存在しない項目は nil を設定
    # ただし、表示名が「＊＊改」のカード（remodel_level = 1 のカード）については、
    # index に 3 加算して配列に入れる（「改」の列に表示されるようにする）
    @ships.each do |ship|
      if ship.is_kai?
        @cards[ship.book_no] = [nil, nil, nil, :not_acquired, :not_acquired, :not_acquired]
      else
        @cards[ship.book_no] = Array.new(ship.variation_num, :not_acquired)
      end
    end

    # 所持カードのフラグを立てる
    # ただし、表示名が「＊＊改」のカードについては、index に 3 加算して配列に入れる（「改」の列に表示されるようにする）
    ShipCard.where(admiral_id: current_admiral.id).includes(:ship_master).each do |card|
      # 未実装の艦娘のデータが不正にインポートされている場合は、単純にそのデータだけ無視する
      next unless @cards.keys.include?(card.book_no)

      # 艦娘一覧の表示範囲かどうかを判定し、必要に応じて表示位置を補正
      idx = card.index_for_ship_list
      if idx && @cards[card.book_no][idx]
        @cards[card.book_no][idx] = :acquired
        @is_blank = false
      end
    end

    # 各艦娘の現在のレベルを調べるために、最後にエクスポートされたデータ（レベルも最大値のはず）を取得
    last_exported_at = ShipStatus.where(admiral_id: current_admiral.id).maximum(:exported_at)

    @statuses = {}
    ShipStatus.where(admiral_id: current_admiral.id, exported_at: last_exported_at).each do |status|
      # 未実装の艦娘のデータが不正にインポートされている場合は、単純にそのデータだけ無視する
      next unless @cards.keys.include?(status.book_no)

      # レベル
      # レベルはノーマルも改も同じなので、両者を区別する必要はない
      @statuses[status.book_no] ||= {}
      @statuses[status.book_no][:level] = status.level

      # 星の数および婚姻状態は remodel_level ごとに別管理
      ship = @ships.select{|s| s.book_no == status.book_no }.first
      if ship
        @statuses[ship.book_no][:star_num] ||= []
        @statuses[ship.book_no][:married] ||= []

        if ship.variation_num == 3 && ship.remodel_level == 1
          # 表示名が「＊＊改」のカードの場合、2列目に表示
          @statuses[status.book_no][:star_num][1] = status.star_num
          @statuses[status.book_no][:married][1] = status.married
        elsif ship.variation_num == 6 && ship.remodel_level < status.remodel_level
          # 改二以上のカードで、remodel_level が ShipMaster の remodel_level より高い場合、2列目に表示
          # 千歳航改、千代田航改はこのパターンに該当する
          @statuses[status.book_no][:star_num][1] = status.star_num
          @statuses[status.book_no][:married][1] = status.married
        else
          # 上記以外の場合は1列目に表示
          @statuses[status.book_no][:star_num][0] = status.star_num
          @statuses[status.book_no][:married][0] = status.married
        end
      end

      # 改装設計図の枚数（NULL の場合は 0 と見なす）
      @statuses[status.book_no][:blueprint_total_num] = status.blueprint_total_num
      @statuses[status.book_no][:blueprint_total_num] ||= 0

      # 艦娘一覧が空ではないことを表すフラグを立てる
      @is_blank = false
    end

    # 特別カードの情報
    @special_ships = SpecialShipMaster.where('implemented_at <= ?', Time.current).order(:book_no, :implemented_at)

    # 特別カードの入手状況を調べる
    # 取得済みは :acquired、未取得は :not_acquired
    # 同一艦娘の特別カードが2枚以上存在しても動作するように、@special_cards のキーに SpecialShipMaster を設定
    @special_cards = {}
    @special_ships.each do |sship|
      exists = ShipCard.exists?(admiral_id: current_admiral.id, book_no: sship.book_no, card_index: sship.card_index)
      @special_cards[sship] = exists ? :acquired : :not_acquired
    end
  end

  # 各艦娘の装備スロットの一覧表示です。
  def slot
    set_meta_tags title: '艦娘一覧（装備スロット）'

    # ship_statuses の最終エクスポート時刻を取得
    # ship_statuses がない場合は、返り値は nil
    last_exported_at = ShipStatus.where(admiral_id: current_admiral.id).maximum('exported_at')

    # ship_master, ship_slot_statuses レコードも含めて一度に取得
    @statuses = ShipStatus.includes(:ship_master, :ship_slot_statuses).where(admiral_id: current_admiral.id, exported_at: last_exported_at)
    @statuses = @statuses.reject{|st| st.ship_master.nil? }
  end

  # 各艦娘の改装設計図の一覧表示です。
  def blueprint
    set_meta_tags title: '改装設計図一覧'

    # blueprint_statuses の最終エクスポート時刻を取得
    # blueprint_statuses がない場合は、返り値は nil
    last_exported_at = BlueprintStatus.where(admiral_id: current_admiral.id).maximum('exported_at')

    # ship_masters レコードも含めて一度に取得
    @statuses = BlueprintStatus.includes(:ship_master).where(admiral_id: current_admiral.id, exported_at: last_exported_at)
    @statuses = @statuses.reject{|st| st.ship_master.nil? }
  end
end

app/helpers/ship_list_helper.rb
module ShipListHelper
  # 引数 status で渡された ship_status に対する、上位の艦娘が着任している場合は true を返します。
  # 例）ノーマルの場合は、改または改二が存在していれば true
  #
  # status: 上位の艦娘がいるか調べたいレコード
  # statuses: ShipStatus の配列
  def upper_level_exists_for?(status, statuses)
    # 艦娘名を取得できない場合は、エラー回避のために false を返す
    return false unless status.ship_master

    statuses.each do |st|
      if st.ship_master.base_ship_name == status.ship_master.base_ship_name && st.remodel_level > status.remodel_level
        return true
      end
    end

    false
  end
end

app/views/ship_list/blueprint.html.erb
<div class="page-header">
  <h2><%= title %></h2>
</div>

<% if @statuses.blank? %>
    <div class="container row">
      <div class="col-sm-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">このページについて</h3>
          </div>
          <div class="panel-body">
            <ul>
              <li><%= link_to '「インポート」', import_url %> ページで種別「改装設計図一覧」の JSON ファイルをアップロードすると、この表に改装設計図の情報が表示されます。</li>
              <li><%= link_to 'エクスポータ（PowerShell 版、Ruby 版）', 'https://github.com/muziyoshiz/admiral_stats_exporter' %> の自動アップロード機能を使う場合は、version 1.7.2 以降にアップデートしてください。</li>
              <li>エクスポータ（ブックマークレット版）の自動アップロードに失敗する場合は、ブラウザのキャッシュを一度削除してみてください。</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
<% else %>
    <div class="container row">
      <div class="col-sm-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">このデータについて</h3>
          </div>
          <div class="panel-body">
            <ul>
              <li>各艦娘の改装設計図の総数と、それぞれの月に有効期限が切れる枚数です。</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="container row summary">
  <div class="col-xl-6 col-lg-6 col-md-6">
    <div class="table-responsive">
      <table id="table-blueprint-summary" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">有効期限</th>
          <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">枚数</th>
        </tr>
        </thead>
        <tbody>
        <% @statuses.map{|s| s.expiration_date }.uniq.sort.each do |expiration_date| %>
            <tr>
              <td class="text-left"><%= expiration_date.to_s(:month) %>末</td>
              <td class="numeric">
                <%= @statuses.select{|s| s.expiration_date == expiration_date }.map{|s| s.blueprint_num }.sum %>
              </td>
            </tr>
        <% end %>
        <tr class="grand-total">
          <td class="text-left">合計</td>
          <td class="numeric"><%= @statuses.map{|s| s.blueprint_num }.sum %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="container">
  <div class="table-responsive">
    <table id="table-blueprint" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-ms-1 col-xs-1">図鑑 No.</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 hidden-xs">艦種</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">艦名</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">有効期限</th>
        <th class="hidden">有効期限（ソートおよび検索用）</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">枚数</th>
        <th class="hidden">枚数（ソートおよび検索用）</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-ms-1 col-xs-1">図鑑 No.</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 hidden-xs">艦種</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">艦名</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">有効期限</th>
        <th class="hidden">有効期限（ソートおよび検索用）</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">枚数</th>
        <th class="hidden">枚数（ソートおよび検索用）</th>
      </tr>
      </tfoot>
      <tbody>
      <% @statuses.each do |status| %>
          <tr>
            <td class="numeric"><%= status.ship_master.book_no %></td>
            <td class="text-left hidden-xs"><%= status.ship_master.ship_type %></td>
            <td class="text-left"><%= status.ship_master.ship_name %></td>
            <td class="text-left"><%= status.expiration_date.to_s(:month) %>末</td>
            <td class="hidden"><%= status.expiration_date.to_i %></td>
            <td class="numeric">
              <%= status.blueprint_num %>
              <span class="blueprint-total-num">/ <%= @statuses.select{|s| s.book_no == status.book_no }.map{|s| s.blueprint_num }.sum %></span>
            </td>
            <td class="hidden"><%= status.blueprint_num %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<script type="application/javascript">
  $(document).ready(function() {
    $('#table-blueprint-summary').DataTable($.extend({}, ADMIRAL_STATS_DATATABLES_DEFAULT, {
      <!-- サマリに検索は不要なため、無効化 -->
      "searching": false,
      <!-- サマリに並び替えは不要なため、無効化 -->
      "ordering": false,
      <!-- サマリに末尾の件数表示は不要なため、無効化 -->
      "info": false,
    }));

    $('#table-blueprint').DataTable($.extend({}, ADMIRAL_STATS_DATATABLES_DEFAULT, {
      "sorting": [ [ 4, "asc" ], [ 5, "desc" ], [ 0, "asc" ] ],
      "aoColumnDefs": [
        <!-- expiration_date で数値通りにソートするための設定 -->
        { "iDataSort": 4, "aTargets": [ 3 ] },
        <!-- blueprint_num で数値通りにソートするための設定 -->
        { "iDataSort": 6, "aTargets": [ 5 ] },
      ],
    }));
  });
</script>

app/views/ship_list/slot.html.erb
<div class="page-header">
  <h2><%= title %></h2>
</div>

<% if @statuses.blank? %>
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">このページについて</h3>
          </div>
          <div class="panel-body">
            <%= link_to '「インポート」', import_url %> ページで種別「艦娘一覧」の JSON ファイルをアップロードすると、この表に装備スロットの情報が表示されます。
          </div>
        </div>
      </div>
    </div>
<% else %>
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">このデータについて</h3>
          </div>
          <div class="panel-body">
            <ul>
              <li>ノーマル艦娘、改艦娘、改二艦娘は装備スロットが分かれているため、両方とも表示しています。</li>
              <li>
                すでに上位カードを入手している艦娘の、それ以外の装備を強調表示しています。装備の整理にお役立てください。
                <ul>
                  <li>例1）すでに吹雪改を入手している場合に、ノーマル吹雪の装備を強調表示</li>
                  <li>例2）すでに北上改二を入手している場合に、ノーマル北上、北上改の装備を強調表示</li>
                </ul>
              </li>
              <li>
                <strong class="text-danger">【装備名が文字化けしている場合】</strong><%= link_to 'PowerShell 版エクスポータ', 'https://github.com/muziyoshiz/admiral_stats_exporter' %> のアップデートをお願いします。この文字化けの不具合は v1.7.1 以降で解決しています。
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div id="select-ship-types" class="container" style="margin-top: 10px;">
  <a id="button-all"                  class="btn btn-primary btn-default">すべて</a>
  <a id="button-normal-only"          class="btn btn-default">ノーマルのみ</a>
  <a id="button-kai-only"             class="btn btn-default">改のみ</a>
  <a id="button-kai2-only"            class="btn btn-default">改二のみ</a>
  <a id="button-ignore-unused-normal" class="btn btn-default">最上位のみ</a>
  <a id="button-unused-normal-only"   class="btn btn-default">上位艦がいる艦娘のみ</a>
</div>

<div class="container">
  <div class="table-responsive">
    <table id="table-ship-book" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-ms-1 col-xs-1">図鑑 No.</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 hidden-xs">艦種</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">艦名</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">改装Lv</th>
        <th class="hidden">改装Lv（ソートおよび検索用）</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">スロット1</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">スロット2</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-ms-2 col-xs-2">スロット3</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-ms-2 col-xs-2">スロット4</th>
        <th class="hidden">表示を優先すべき艦がいるか（フィルタ用）</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th class="text-left">図鑑 No.</th>
        <th class="text-left hidden-xs">艦種</th>
        <th class="text-left">艦名</th>
        <th class="text-left col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">改</th>
        <th class="hidden">改（ソートおよび検索用）</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">スロット1</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">スロット2</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-ms-2 col-xs-2">スロット3</th>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-ms-2 col-xs-2">スロット4</th>
        <th class="hidden">表示を優先すべき艦がいるか（フィルタ用）</th>
      </tr>
      </tfoot>
      <tbody>
      <% @statuses.each do |status| %>
          <%
            upper_level_exists = upper_level_exists_for?(status, @statuses)
          %>
          <tr <%== 'class="unused-normal"' if upper_level_exists %>>
            <td class="numeric"><%= status.ship_master.book_no %></td>
            <td class="text-left hidden-xs"><%= status.ship_master.ship_type_by_status(status) %></td>
            <td class="text-left"><%= status.ship_master.ship_name %></td>
            <td class="text-left">
              <%
                remodel_lv = case status.remodel_level
                               when 1
                                 '改'
                               when 2
                                 '改二'
                               when 3
                                 '改三'
                               when 4
                                 '改四'
                               when 5
                                 '改五'
                               else
                                 # ノーマル艦娘のみを検索するための文字列
                                 '<span class="hidden">N</span>'
                             end
              %>
              <%= remodel_lv.html_safe %>
            </td>
            <td class="hidden"><%= status.remodel_level %></td>
            <% 4.times.each do |idx| %>
                <% slot = status.ship_slot_statuses[idx] %>
                <% if slot and slot.slot_index == idx %>
                    <td class="text-left slot">
                      <span class="slot-equip-name">
                        <%= slot.slot_equip_name %>
                        <% if slot.is_equipped_aircraft? %>
                            (<%= slot.slot_amount %>)
                        <% end %>
                      </span>
                      <% if slot.is_not_equipped_aircraft? %>
                          <span class="not-equipped">(<%= slot.slot_amount %>)</span>
                      <% end %>
                    </td>
                <% else %>
                    <td class="none"><i class="glyphicon glyphicon-minus"></i></td>
                <% end %>
            <% end %>
            <td class="hidden"><%= upper_level_exists %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<script type="application/javascript">
  $(document).ready(function() {
    var table = $('#table-ship-book').DataTable($.extend({}, ADMIRAL_STATS_DATATABLES_DEFAULT, {
      "aoColumnDefs": [
        <!-- remodel_level で数値通りにソートするための設定 -->
        { "iDataSort": 4, "aTargets": [ 3 ] },
      ],
    }));

    // 与えられたイベントに基づいて、ボタンのハイライト表示および検索条件の変更を行います。
    function selectCondition(e, remodel, unusedNormal) {
      e.preventDefault();
      $('#select-ship-types').children('a').removeClass('btn-primary');
      $(e.currentTarget).addClass('btn-primary');
      table.columns(4).search(remodel);
      table.columns(9).search(unusedNormal).draw();
    }

    $('#button-all'                 ).on('click', function (e) { selectCondition(e, '',  ''); } );
    $('#button-normal-only'         ).on('click', function (e) { selectCondition(e, '0', ''); } );
    $('#button-kai-only'            ).on('click', function (e) { selectCondition(e, '1', ''); } );
    $('#button-kai2-only'           ).on('click', function (e) { selectCondition(e, '2', ''); } );
    $('#button-ignore-unused-normal').on('click', function (e) { selectCondition(e, '',  'false'); } );
    $('#button-unused-normal-only'  ).on('click', function (e) { selectCondition(e, '',  'true'); } );
  });
</script>