config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 過去のお知らせ
  get 'notice', to: 'notice#index', as: :notice

  # 使い方
  get 'manual/exporter', to: 'manual#exporter'

  # インポート
  get 'import', to: 'import#index', as: :import
  post 'import/file', to: 'import#file'
  post 'import/generate_token', to: 'import#generate_token'

  # エクスポート
  get 'export', to: 'export#index', as: :export
  get 'export/admiral_statuses', to: 'export#admiral_statuses'
  get 'export/event_progress_statuses', to: 'export#event_progress_statuses'
  get 'export/cop_event_progress_statuses', to: 'export#cop_event_progress_statuses'
  get 'export/ship_statuses', to: 'export#ship_statuses'

  # 提督情報
  match 'admiral_info', to: 'admiral_info#index', via: [ :get, :post ]
  get 'admiral_info/event(/:event_no(/:period))', to: 'admiral_info#event'
  get 'admiral_info/cop_event(/:event_no)', to: 'admiral_info#cop_event'

  # 艦娘情報
  ## 表が主体のページ
  get 'ship_list', to: 'ship_list#index'
  get 'ship_list/slot', to: 'ship_list#slot'
  get 'ship_list/blueprint', to: 'ship_list#blueprint'
  ## グラフが主体のページ
  match 'ship_info/level', to: 'ship_info#level', via: [ :get, :post ]
  match 'ship_info/level_summary', to: 'ship_info#level_summary', via: [ :get, :post ]
  match 'ship_info/card', to: 'ship_info#card', via: [ :get, :post ]

  # 装備情報
  get 'equipment_list', to: 'equipment_list#index'
  match 'equipment_list/:book_no', to: 'equipment_list#show', via: [ :get, :post ]

  # 全提督との比較
  get 'global/ship_card_ownership', to: 'global#ship_card_ownership', as: :global_ship_card_ownership
  get 'global/ship_card_ownership/active/:def_of_active_users', to: 'global#ship_card_ownership'
  get 'global/ship_card_ownership/event/:event_no', to: 'global#event_ship_card_ownership'
  get 'global/event(/:event_no(/:period))', to: 'global#event'
  get 'global/cop_event(/:event_no)', to: 'global#cop_event'

  get 'friend', to: 'friend#index'

  # Admiral Stats について
  get 'about', to: 'about#index'

  # OmniAuth によるログイン・ログアウト
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # デバッグ用のログイン（development のみ有効）
  get 'sessions/debug_create/:uid/:nickname', to: 'sessions#debug_create'

  # 以下の記載を追加すると root_url メソッドも自動設定される
  root to: 'home#index'

  # Public play data
  scope '/@:url_name' do
    # 公開情報の種類が2種類以上になったら、リダイレクト処理を変更する
    get '/', to: redirect('/@%{url_name}/ship_list')
    get '/ship_list', to: 'public_ship_list#index'
    get '/equipment_list', to: 'public_equipment_list#index'
    match '/equipment_list/:book_no', to: 'public_equipment_list#show', via: [ :get, :post ]
  end
  # 古い URL を、互換性維持のために残す
  get 'admirals/:url_name/ship_list', to: redirect('/@%{url_name}'), constraints: { format: :html }

  # Settings
  scope 'settings' do
    get 'request_logs', to: 'request_log#index'
    get 'tokens', to: 'token#index'
    post 'tokens', to: 'token#create'
    get 'publications', to: 'publication#index'
    post 'publications', to: 'publication#create_or_update'
  end

  # API
  scope 'api/v1' do
    # Admiral Stats がインポート可能なファイル種別のリスト（snake_case）
    get 'import/file_types', to: 'api_import#file_types'

    # SEGA 公式からエクスポートしたプレイデータのインポート
    post 'import/:file_type/:timestamp', to: 'api_import#import', as: :api_import
  end

  # 上記のいずれにもマッチしなかった場合は、root にリダイレクト
  get '*unmatched_route', to: 'application#redirect_to_home'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate, except: :index

  def index
    # ホーム画面にだけ色々情報を設定する
    set_meta_tags title: '艦これアーケードのプレイデータ管理ツール',
                  description: 'Admiral Stats は、艦これアーケードのプレイヤーズサイトからエクスポートできる自分のプレイデータを、時系列に可視化するツールです。',
                  # Open Graph Protocol (OGP)
                  og: {
                      # Page title（title と同じ値が設定される）
                      title: :title,
                      type: 'website',
                      image: 'https://www.admiral-stats.com/images/sample.png',
                      # Canonical URL（canonical と同じ値が設定される）
                      url: :canonical,
                      # Site title（site と同じ値が設定される）
                      site_name: :site,
                      # Page description（description と同じ値が設定される）
                      description: :description,
                      locale: 'ja_JP',
                  },
                  # Twitter Card
                  twitter: {
                      # Summary Card with Large Image
                      # https://dev.twitter.com/cards/types/summary-large-image
                      card: 'summary_large_image',
                      site: '@muziyoshiz',
                      title: :title,
                      description: :description,
                      image: 'https://www.admiral-stats.com/images/sample.png',
                  }

    # ログイン前の場合はゲストユーザ用ページを表示
    unless logged_in?
      render :action => 'index_guest'
      return
    end

    # 入手済みのカードのデータを全入手
    ship_cards = ShipCard.where(admiral_id: current_admiral.id).includes(:ship_master)

    # 艦娘図鑑データがない場合
    if ship_cards.blank?
      return
    end

    special_ship_masters = {}
    SpecialShipMaster.all.each do |master|
      special_ship_masters[master.book_no] ||= {}
      special_ship_masters[master.book_no][master.card_index] = master
    end

    # 活動記録を格納する配列
    @histories = []

    # カード種別ごとの数を数えるカウンター
    # 0, 1, 2 -> ノーマルの通常、ホロ、中破
    # 3, 4, 5 -> 改の通常、ホロ、中破
    # 6, 7, 8 -> 改二の通常、ホロ、中破
    # 9, 10, 11 -> 改三以上の通常、ホロ、中破
    counters = Array.new(12, 0)

    # カードをソートするためのインデックス
    index = 0

    ship_cards.sort_by{|c| [ c.first_exported_at, c.book_no ] }.each do |card|
      # 活動記録への表示内容を取得する
      desc, clazz = resolve_desc_and_clazz(card, counters)

      # 通常の艦娘カードのマスタデータに含まれない場合は、限定カードから探す
      # TODO 今後、限定カードのレアリティが増えたら、分岐を書き足す（コードが無駄に長くなるので、全パターンは書かない）
      unless desc
        master = card.ship_master
        sp_master = special_ship_masters[card.book_no][card.card_index]
        if sp_master
          card_index = sp_master.remodel_level * 3 + sp_master.rarity
          counters[card_index] += 1

          case sp_master.remodel_level
            when 0
              case sp_master.rarity
                when 1
                  desc = "#{master.ship_name}（ホロ・限定カード） が着任しました。通算 #{counters[card_index]} 隻目のホロです。"
                  clazz = 'holo'
              end
            when 1
              # 辞書の艦娘名に「改」を付ける必要があるかどうかを判定
              kai = '改' if sp_master.card_index == 6

              case sp_master.rarity
                when 1
                  desc = "#{master.ship_name}#{kai}（ホロ・限定カード） が着任しました。通算 #{counters[card_index]} 隻目の改（ホロ）です。"
                  clazz = 'kai-holo'
              end
            when 2
              case sp_master.rarity
                when 0
                  desc = "#{master.ship_name}（限定カード） が着任しました。通算 #{counters[card_index]} 隻目の改二です。"
                  clazz = 'kai2'
                when 1
                  desc = "#{master.ship_name}（ホロ・限定カード） が着任しました。通算 #{counters[card_index]} 隻目の改二（ホロ）です。"
                  clazz = 'kai2-holo'
              end
          end
        end
      end

      if desc
        @histories << {
            :exported_at => card.first_exported_at.to_s(:datetime),
            :index => index,
            :description => desc,
            :class => clazz,
        }

        index += 1
      end
    end
  end

  private

  # 艦娘カードの情報から、活動記録に表示する説明文と、CSS のクラス名を解決して返します。
  # また、カウンターにカード枚数を加算します。
  def resolve_desc_and_clazz(card, counters)
    master = card.ship_master
    card_index = card.card_index

    if master.book_no == 205
      case card_index
        when 3
          # 限定カードの場合はこの処理全体をスキップ
          return nil, nil
        when 4..6
          # 春雨改の card_index を補正
          card_index -= 1
      end
    end

    # TODO (remodel_level, card_index) の組み合わせと、レアリティの対応テーブルを用意して、コード短縮する
    case master.remodel_level
      when 0
        counters[card_index] += 1 if card_index.between?(0, 5)
        case card_index
          when 0
            return "#{master.ship_name} が着任しました。", nil
          when 1
            return "#{master.ship_name}（ホロ） が着任しました。通算 #{counters[1]} 隻目のホロです。", 'holo'
          when 2
            return "#{master.ship_name}（中破） が着任しました。通算 #{counters[2]} 隻目の中破です。", 'chuha'
          when 3
            return "#{master.ship_name}改 が着任しました。通算 #{counters[3]} 隻目の改です。", 'kai'
          when 4
            return "#{master.ship_name}改（ホロ） が着任しました。通算 #{counters[4]} 隻目の改（ホロ）です。", 'kai-holo'
          when 5
            return "#{master.ship_name}改（中破） が着任しました。通算 #{counters[5]} 隻目の改（中破）です。", 'kai-chuha'
        end
      when 1
        counters[card_index + 3] += 1 if card_index.between?(0, 2)
        case card_index
          when 0
            return "#{master.ship_name} が着任しました。通算 #{counters[3]} 隻目の改です。", 'kai'
          when 1
            return "#{master.ship_name}（ホロ） が着任しました。通算 #{counters[4]} 隻目の改（ホロ）です。", 'kai-holo'
          when 2
            return "#{master.ship_name}（中破） が着任しました。通算 #{counters[5]} 隻目の改（中破）です。", 'kai-chuha'
        end
      when 2
        counters[card_index + 6] += 1 if card_index.between?(0, 2)
        case card_index
          when 0
            return "#{master.ship_name} が着任しました。通算 #{counters[6]} 隻目の改二です。", 'kai2'
          when 1
            return "#{master.ship_name}（ホロ） が着任しました。通算 #{counters[7]} 隻目の改二（ホロ）です。", 'kai2-holo'
          when 2
            return "#{master.ship_name}（中破） が着任しました。通算 #{counters[8]} 隻目の改二（中破）です。", 'kai2-chuha'
        end
      when 3..5
        # remodel_level が 3 以上の艦娘は、すべて「改三以上」として扱う
        counters[(card_index % 3) + 9] += 1 if card_index.between?(0, 5)

        # 艦娘名表示は、名前に「改」を付けるか付けないかを判断するために、remodel_level で処理を分岐する必要がある
        case master.remodel_level
          when 3
            # 千歳航、千代田航、およびコンバート艦娘がここに該当
            case card_index
              when 0
                return "#{master.ship_name} が着任しました。通算 #{counters[9]} 隻目の改三以上です。", 'kai3'
              when 1
                return "#{master.ship_name}（ホロ） が着任しました。通算 #{counters[10]} 隻目の改三以上（ホロ）です。", 'kai3-holo'
              when 2
                return "#{master.ship_name}（中破） が着任しました。通算 #{counters[11]} 隻目の改三以上（中破）です。", 'kai3-chuha'
              when 3
                return "#{master.ship_name}改 が着任しました。通算 #{counters[9]} 隻目の改三以上です。", 'kai3'
              when 4
                return "#{master.ship_name}改（ホロ） が着任しました。通算 #{counters[10]} 隻目の改三以上（ホロ）です。", 'kai3-holo'
              when 5
                return "#{master.ship_name}改（中破） が着任しました。通算 #{counters[11]} 隻目の改三以上（中破）です。", 'kai3-chuha'
            end
          when 5
            # 千歳航改二、千代田航改二のみがここに該当
            case card_index
              when 0
                return "#{master.ship_name} が着任しました。通算 #{counters[9]} 隻目の改三以上です。", 'kai3'
              when 1
                return "#{master.ship_name}（ホロ） が着任しました。通算 #{counters[10]} 隻目の改三以上（ホロ）です。", 'kai3-holo'
              when 2
                return "#{master.ship_name}（中破） が着任しました。通算 #{counters[11]} 隻目の改三以上（中破）です。", 'kai3-chuha'
            end
        end
    end

    return nil, nil
  end
end

app/views/home/_history.html.erb
<div class="container">
  <div class="table-responsive">
    <table id="table-history" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th class="text-left col-xl-2 col-lg-2 col-md-2 col-sm-3 col-xs-4">日時</th>
        <th class="hidden">インデックス（ソート用）</th>
        <th class="text-left col-xl-10 col-lg-10 col-md-10 col-sm-9 col-xs-8">活動記録</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th class="text-left">日時</th>
        <th class="hidden">インデックス（ソート用）</th>
        <th class="text-left">活動記録</th>
      </tr>
      </tfoot>
      <tbody>
      <% histories.each do |history| %>
          <tr class="history">
            <td class="text-left"><%= history[:exported_at] %></td>
            <td class="hidden"><%= history[:index] %></td>
            <td class="text-left <%== history[:class] if history[:class] %>"><%= history[:description] %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<script type="application/javascript">
  $(document).ready(function() {
    $('#table-history').DataTable($.extend({}, ADMIRAL_STATS_DATATABLES_DEFAULT, {
      "paging": true,
      "sorting": [ 0, "desc" ],
      "aoColumnDefs": [
        <!-- インデックスでソートするための設定 -->
        { "iDataSort": 1, "aTargets": [ 0 ] },
        { orderable: false, targets: [ 2 ] }
      ],
    }));
  } );
</script>

app/views/home/_notice.html.erb
<div class="panel-heading">
  <h3 class="panel-title">お知らせ</h3>
</div>
<div class="panel-body">
  <ul>
    <li>
      最新のお知らせは <%= link_to 'Twitter アカウント', twitter_admiral_stats_url, target: '_blank' %> にて公開中。不具合報告もこちらにお願いします。<br>
      <div class="follow-button">
        <a href="https://twitter.com/admiral_stats" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @admiral_stats</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </div>
    </li>
    <li>
      2019年8月31日更新：プレイデータのエクスポート機能を追加しました。<%= link_to_if_logged_in '「エクスポート」ページ', export_url %> からご利用いただけます。
    </li>
    <li>
      2019年7月27日更新：9月末をもって Admiral Stats のサービス提供を終了します。詳しいスケジュールは <%= link_to 'Admiral Stats のサービス提供のお知らせ', 'https://muziyoshiz.hatenablog.com/entry/2019/07/27/191007', target: '_blank' %>をご覧ください。
    </li>
    <li>
      <%= link_to '過去のお知らせ...', notice_url %>
    </li>
  </ul>
</div>

app/views/home/index.html.erb
<div class="page-header">
  <h2><%= image_tag 'icon.png', size: '80x80' %> Admiral Stats</h2>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-info">
      <% if @histories.blank? %>
          <div class="panel-heading">
            <h3 class="panel-title">はじめての方へ</h3>
          </div>
          <div class="panel-body">
            <p>
              Admiral Stats は、<%= link_to '艦これ Arcade のプレイヤーズサイト', sega_url, :target => '_blank' %>
              からエクスポートできる自分のプレイデータを、時系列で可視化するツールです。
              <br>
              カードの枚数が増えていく様子や、艦娘のレベルが上がっていく様子を見るのが楽しい、という提督のために作りました。
            </p>
            SEGA ID が未登録の方は、まずは SEGA ID を登録して、プレイヤーズサイトにログインできることを確認してください。
            <br>
            そのあとで <%= link_to '「使い方」', controller: 'manual', action: 'exporter' %> の手順に従い、自分のプレイデータを Admiral Stats にインポートしてみてください。
          </div>
      <% else %>
          <%= render( partial: 'notice' ) %>
      <% end %>
    </div>
  </div>
</div>

<%= render( partial: 'history', locals: { histories: @histories } ) if @histories %>

app/views/home/index_guest.html.erb
<div class="page-header">
  <h2><%= image_tag 'icon.png', size: '80x80' %> Admiral Stats</h2>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-info">
      <%= render( partial: 'notice' ) %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h3>Admiral Stats って何？</h3>
    <p>
      Admiral Stats は艦これアーケードのプレイデータを表示するサイトです。<br>
      <%= link_to 'SEGA 公式のプレイヤーズサイト', sega_url, :target => '_blank' %>
      が対応していない、時系列での可視化に対応しています。また、<%= link_to '他提督との比較機能', controller: 'global', action: 'event' %>、プレイデータ公開機能なども備えています。
    </p>
    <h4 class="text-info">サンプル 1：カードの入手履歴</h4>
    <p>
      <%= image_tag 'home/sample_home.png', class: 'img-responsive img-thumbnail' %>
    </p>
    <h4 class="text-info">サンプル 2：レベル・経験値のグラフ</h4>
    <p>
      <%= image_tag 'home/sample_chart_level.png', class: 'img-responsive img-thumbnail' %>
    </p>
    <h4 class="text-info">サンプル 3：レベル上限到達予想日（レベル150にも対応）</h4>
    <p>
      <%= image_tag 'home/sample_lv99_forecast.png', class: 'img-responsive img-thumbnail' %>
    </p>
    <h4 class="text-info">サンプル 4：カード入手状況の一覧表示</h4>
    <p>
      <%= image_tag 'home/sample_ship_list.png', class: 'img-responsive img-thumbnail' %>
    </p>
    <h4 class="text-info">サンプル 5：イベントの進捗履歴</h4>
    <p>
      <%= image_tag 'home/sample_event_progress.png', class: 'img-responsive img-thumbnail' %>
    </p>
  </div>
  <div class="col-md-6">
    <h3>ログイン／ユーザ登録</h3>
    <p>
      ログインには Twitter のアカウントが必要です。初回ログイン時に Admiral Stats へのユーザ登録が行われます。
    </p>
    <p>
      Admiral Stats は Twitter アカウントをログインのみに用います。ユーザ登録前に、
      <%= link_to 'Admiral Stats について', :controller => 'about' %> のプライバシーポリシーおよび免責事項をご確認ください。
    </p>
    <p>
      <%= link_to 'Twitter アカウントでログイン／ユーザ登録', root_url + 'auth/twitter', class: 'btn btn-primary' %>
    </p>

    <hr>

    <h3>データのアップロード方法は？</h3>
    <p>
      艦これ Arcade をプレイするたびに、SEGA 公式のプレイヤーズサイトの情報が更新されます。
    </p>
    <p>
      情報が更新されるたびに、以下の手順で、プレイヤーズサイトからデータをダウンロードし、Admiral Stats
      へアップロードしてください。プレイのたびにアップロードを繰り返すことで、時系列データが溜まっていきます。
    </p>
    <ol class="guest">
      <li>
        SEGA 公式のプレイヤーズサイトからの、データのエクスポート（ダウンロード）
        <ul>
          <li>
            <%= link_to 'プレイヤーズサイト', sega_url, :target => '_blank' %>
            はデータのエクスポート機能を提供していないため、何らかの非公式な手段でデータをエクスポートする必要があります。
          </li>
          <li>
            データのエクスポート方法については、<%= link_to '「使い方」ページ', controller: 'manual', action: 'exporter' %> をご覧ください。
          </li>
        </ul>
      </li>
      <li>
        Admiral Stats への、データのインポート（アップロード）
        <ul>
          <li>
            手順 1 でダウンロードした JSON ファイルは、エクスポータの自動アップロード機能を使うか、
            Admiral Stats の「インポート」ページを使ってアップロードできます。
          </li>
          <li>
            アップロード完了すると、各種グラフや一覧表が、自動的に更新されます。
          </li>
        </ul>
      </li>
    </ol>
    <p>
      <%= image_tag 'home/admiral_stats_concept.png', class: 'img-responsive img-thumbnail' %>
    </p>

    <hr>

    <h3>紹介スライド（LT 発表資料）</h3>
    <script async class="speakerdeck-embed" data-id="f50c7d109361420bbc0ee31b2c44d54e" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>
  </div>
</div>