config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 過去のお知らせ
  get 'notice', to: 'notice#index', as: :notice

  # 使い方
  get 'manual/exporter', to: 'manual#exporter'

  # インポート
  get 'import', to: 'import#index', as: :import
  post 'import/file', to: 'import#file'
  post 'import/generate_token', to: 'import#generate_token'

  # エクスポート
  get 'export', to: 'export#index', as: :export
  get 'export/admiral_statuses', to: 'export#admiral_statuses'
  get 'export/event_progress_statuses', to: 'export#event_progress_statuses'
  get 'export/cop_event_progress_statuses', to: 'export#cop_event_progress_statuses'
  get 'export/ship_statuses', to: 'export#ship_statuses'

  # 提督情報
  match 'admiral_info', to: 'admiral_info#index', via: [ :get, :post ]
  get 'admiral_info/event(/:event_no(/:period))', to: 'admiral_info#event'
  get 'admiral_info/cop_event(/:event_no)', to: 'admiral_info#cop_event'

  # 艦娘情報
  ## 表が主体のページ
  get 'ship_list', to: 'ship_list#index'
  get 'ship_list/slot', to: 'ship_list#slot'
  get 'ship_list/blueprint', to: 'ship_list#blueprint'
  ## グラフが主体のページ
  match 'ship_info/level', to: 'ship_info#level', via: [ :get, :post ]
  match 'ship_info/level_summary', to: 'ship_info#level_summary', via: [ :get, :post ]
  match 'ship_info/card', to: 'ship_info#card', via: [ :get, :post ]

  # 装備情報
  get 'equipment_list', to: 'equipment_list#index'
  match 'equipment_list/:book_no', to: 'equipment_list#show', via: [ :get, :post ]

  # 全提督との比較
  get 'global/ship_card_ownership', to: 'global#ship_card_ownership', as: :global_ship_card_ownership
  get 'global/ship_card_ownership/active/:def_of_active_users', to: 'global#ship_card_ownership'
  get 'global/ship_card_ownership/event/:event_no', to: 'global#event_ship_card_ownership'
  get 'global/event(/:event_no(/:period))', to: 'global#event'
  get 'global/cop_event(/:event_no)', to: 'global#cop_event'

  get 'friend', to: 'friend#index'

  # Admiral Stats について
  get 'about', to: 'about#index'

  # OmniAuth によるログイン・ログアウト
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # デバッグ用のログイン（development のみ有効）
  get 'sessions/debug_create/:uid/:nickname', to: 'sessions#debug_create'

  # 以下の記載を追加すると root_url メソッドも自動設定される
  root to: 'home#index'

  # Public play data
  scope '/@:url_name' do
    # 公開情報の種類が2種類以上になったら、リダイレクト処理を変更する
    get '/', to: redirect('/@%{url_name}/ship_list')
    get '/ship_list', to: 'public_ship_list#index'
    get '/equipment_list', to: 'public_equipment_list#index'
    match '/equipment_list/:book_no', to: 'public_equipment_list#show', via: [ :get, :post ]
  end
  # 古い URL を、互換性維持のために残す
  get 'admirals/:url_name/ship_list', to: redirect('/@%{url_name}'), constraints: { format: :html }

  # Settings
  scope 'settings' do
    get 'request_logs', to: 'request_log#index'
    get 'tokens', to: 'token#index'
    post 'tokens', to: 'token#create'
    get 'publications', to: 'publication#index'
    post 'publications', to: 'publication#create_or_update'
  end

  # API
  scope 'api/v1' do
    # Admiral Stats がインポート可能なファイル種別のリスト（snake_case）
    get 'import/file_types', to: 'api_import#file_types'

    # SEGA 公式からエクスポートしたプレイデータのインポート
    post 'import/:file_type/:timestamp', to: 'api_import#import', as: :api_import
  end

  # 上記のいずれにもマッチしなかった場合は、root にリダイレクト
  get '*unmatched_route', to: 'application#redirect_to_home'
end

app/controllers/export_controller.rb
class ExportController < ApplicationController
  before_action :authenticate

  LIMIT = 100000

  def index
    set_meta_tags title: 'エクスポート'

    @admiral_status_count = AdmiralStatus.where(admiral_id: current_admiral.id).count
    @event_progress_status_count = EventProgressStatus.where(admiral_id: current_admiral.id).count
    @cop_event_progress_status_count = CopEventProgressStatus.where(admiral_id: current_admiral.id).count
    @ship_status_count = ShipStatus.where(admiral_id: current_admiral.id).count

    @ship_status_pages = (@ship_status_count.to_f / LIMIT).ceil
  end

  def admiral_statuses
    @admiral_statuses = AdmiralStatus.where(admiral_id: current_admiral.id).order(:exported_at)

    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: 'admiral_statuses.csv', type: :csv
      end
    end
  end

  def event_progress_statuses
    @event_progress_statuses = EventProgressStatus.where(admiral_id: current_admiral.id).
        order(:exported_at).order(:event_no).order(:level).order(:period)

    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: 'event_progress_statuses.csv', type: :csv
      end
    end
  end

  def cop_event_progress_statuses
    @cop_event_progress_statuses = CopEventProgressStatus.where(admiral_id: current_admiral.id).
        order(:exported_at).order(:event_no)

    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: 'cop_event_progress_statuses.csv', type: :csv
      end
    end
  end

  def ship_statuses
    page = params[:page]

    if page
      offset = (page.to_i - 1) * LIMIT

      @ship_statuses = ShipStatus.where(admiral_id: current_admiral.id).
          order(:exported_at).order(:book_no).order(:remodel_level).limit(LIMIT).offset(offset)

      respond_to do |format|
        format.csv do
          send_data render_to_string, filename: "ship_statuses_#{page}.csv", type: :csv
        end
      end
    else
      @ship_statuses = ShipStatus.where(admiral_id: current_admiral.id).
          order(:exported_at).order(:book_no).order(:remodel_level).limit(LIMIT)

      respond_to do |format|
        format.csv do
          send_data render_to_string, filename: 'ship_statuses.csv', type: :csv
        end
      end
    end
  end
end

app/views/export/index.html.erb
<div class="page-header">
  <%= render partial: 'messages', locals: {messages: @messages, error: @error} %>
  <h2><%= title %></h2>
</div>

<div class="container" style="margin-top: 18px;">
  <div class="row">
    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">エクスポート方法</div>
        <div class="panel-body">
          <ul>
            <li>
              以下のリンクをクリックすると、プレイデータを CSV ファイルとしてダウンロードできます。
            </li>
            <li>
              1ファイルのダウンロードに数分かかる場合があります。ファイルが1つダウンロードし終わってから、次のファイルのダウンロードをお願いします。
            </li>
            <li>
              複数ファイルを同時にダウンロードすると、ダウンロードに失敗する場合があります（特に、プレイデータ量の多い方）。
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <ul>
    <li>
      <%= link_to '提督情報 - 基本情報 (admiral_statuses.csv)', export_admiral_statuses_path(format: :csv) %> (<%= @admiral_status_count.to_s(:delimited) %> 件)
    </li>
    <li>
      <%= link_to '提督情報 - イベントの進捗 (event_progress_statuses.csv)', export_event_progress_statuses_path(format: :csv) %> (<%= @event_progress_status_count.to_s(:delimited) %> 件)
    </li>
    <li>
      <%= link_to '提督情報 - 輸送イベントの進捗 (cop_event_progress_statuses.csv)', export_cop_event_progress_statuses_path(format: :csv) %> (<%= @cop_event_progress_status_count.to_s(:delimited) %> 件)
    </li>
    <% if @ship_status_pages > 1 %>
        <li>
          艦娘情報 (<%= @ship_status_count.to_s(:delimited) %> 件)
          <ul>
            <% 1.upto @ship_status_pages do |page_num| %>
                <li>
                  <%= link_to "ship_statuses_#{page_num}.csv", export_ship_statuses_path(page: page_num, format: :csv) %>
                </li>
            <% end %>
          </ul>
        </li>
    <% else %>
        <li>
          <%= link_to '艦娘情報 (ship_statuses.csv)', export_ship_statuses_path(format: :csv) %> (<%= @ship_status_count.to_s(:delimited) %> 件)
        </li>
    <% end %>
  </ul>
</div>